version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: store-app-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    networks:
      - backend
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    container_name: store-app-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://store-app-db:5432/storeapp?useSSL=false
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - backend

volumes:
  db:
    driver: local

networks:
  backend: