-- populate the CLUSTER table
INSERT INTO CLUSTER VALUES (1, 'Europe')
INSERT INTO CLUSTER VALUES (2, 'Asia')
INSERT INTO CLUSTER VALUES (3, 'USA')

-- populate the REGION table
INSERT INTO REGION (ID, NAME, TYPE, CLUSTER_ID) VALUES (1, 'North EU', 'XY', 1)
INSERT INTO REGION (ID, NAME, TYPE, CLUSTER_ID) VALUES (2, 'South EU', 'XY', 1)
INSERT INTO REGION (ID, NAME, TYPE, CLUSTER_ID) VALUES (3, 'North AS', 'ZZ', 2)
INSERT INTO REGION (ID, NAME, TYPE, CLUSTER_ID) VALUES (4, 'South AS', 'ZZ', 2)
INSERT INTO REGION (ID, NAME, TYPE, CLUSTER_ID) VALUES (5, 'Japan', 'JP', 2)

-- populate the STORE table
INSERT INTO STORE (ID, NAME, THEME, REGION_ID) VALUES (1, 'A body store', 'What an a rattly Store!', 1)
INSERT INTO STORE (ID, NAME, THEME, REGION_ID) VALUES (2, 'A body store', 'What an a rattly Store!', 2)
INSERT INTO STORE (ID, NAME, THEME, REGION_ID) VALUES (3, 'A hundredth store', 'A paneled store focused on a salad', 2)

-- populate the ALLSTOREDATA table
INSERT INTO PRODUCT (ID, CLUSTER, REGION, REGION_TYPE, STORE_NAME, STORE_THEME, PRODUCT_MODEL, PRODUCT_SIZE, PRODUCT_SKU, PRODUCT_EAN, PRODUCT_DESC, PRODUCT_SEASON) VALUES (1, 'Europe', 'South EU', 'XY', 'A body store', 'What an a rattly Store!', 'PD0_HEXAGON', 'XS', '12000000-XS', 9747994062149, 'Quis officia eu consectetur irure nostrud et proident aliquip qui.', 'S18')
INSERT INTO PRODUCT (ID, CLUSTER, REGION, REGION_TYPE, STORE_NAME, STORE_THEME, PRODUCT_MODEL, PRODUCT_SIZE, PRODUCT_SKU, PRODUCT_EAN, PRODUCT_DESC, PRODUCT_SEASON) VALUES (2, 'Europe', 'North EU', 'XY', 'A body store', 'What an a rattly Store!', 'PD0_HEXAGON', 'XS', '12000000-XS', 9747994062149, 'Quis officia eu consectetur irure nostrud et proident aliquip qui.', 'S18')
INSERT INTO PRODUCT (ID, CLUSTER, REGION, REGION_TYPE, STORE_NAME, STORE_THEME, PRODUCT_MODEL, PRODUCT_SIZE, PRODUCT_SKU, PRODUCT_EAN, PRODUCT_DESC, PRODUCT_SEASON) VALUES (3, 'Europe', 'North EU', 'XY', 'A hundredth store', 'What an a rattly Store!', 'PD0_HEXAGON', 'XS', '12000000-XS', 9747994062149, 'Quis officia eu consectetur irure nostrud et proident aliquip qui.', 'S17')

-- populate the AVAILABLE_FIELD table
INSERT INTO AVAILABLE_FIELD (ID, NAME, DB_FIELD_NAME) VALUES (1, 'Season', 'productSeason')
INSERT INTO AVAILABLE_FIELD (ID, NAME, DB_FIELD_NAME) VALUES (2, 'Cluster', 'cluster')
INSERT INTO AVAILABLE_FIELD (ID, NAME, DB_FIELD_NAME) VALUES (3, 'Region', 'region')
INSERT INTO AVAILABLE_FIELD (ID, NAME, DB_FIELD_NAME) VALUES (4, 'Region Type', 'regionType')
INSERT INTO AVAILABLE_FIELD (ID, NAME, DB_FIELD_NAME) VALUES (5, 'Model', 'productModel')
INSERT INTO AVAILABLE_FIELD (ID, NAME, DB_FIELD_NAME) VALUES (6, 'Size', 'productSize')
INSERT INTO AVAILABLE_FIELD (ID, NAME, DB_FIELD_NAME) VALUES (7, 'SKU', 'productSku')
INSERT INTO AVAILABLE_FIELD (ID, NAME, DB_FIELD_NAME) VALUES (8, 'Store Name', 'storeName')
INSERT INTO AVAILABLE_FIELD (ID, NAME, DB_FIELD_NAME) VALUES (9, 'Store Theme', 'storeTheme')

